name: Build & Release App

# 触发条件：手动触发或标签推送
on:
  workflow_dispatch:
  push:

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      # 步骤1：签出代码
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: "false"

      # 步骤10：强制触发 MirrorChyan 上传
      - name: Trigger MirrorChyanUploading
        shell: bash
        run: |
          gh workflow run --repo $GITHUB_REPOSITORY 'MirrorChyan Uploading'
          gh workflow run --repo $GITHUB_REPOSITORY 'MirrorChyan Release Note'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
